"""Render a work order (dict) to a professional PDF via ReportLab.

Best-effort: callers guard the import so the demo runs even without reportlab.
"""

from __future__ import annotations

from pathlib import Path

OUT_DIR = Path("./out")


def render(wo: dict, out_dir: str | Path = OUT_DIR) -> str:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{wo['wo_id']}.pdf"

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(str(path), pagesize=LETTER, title=wo["wo_id"])
    lo, hi = wo["estimated_impact_usd"]
    rows = [
        ["Work Order", wo["wo_id"]],
        ["Equipment", f"{wo['equipment_name']} ({wo['equipment_id']})"],
        ["Line", wo["line"]],
        ["Severity", wo["severity"].upper()],
        ["Root cause", wo["root_cause"]],
        ["Parts", "\n".join(wo["parts"])],
        ["Technician", wo["technician"]],
        ["ETA (hours)", str(wo["eta_hours"])],
        ["Est. impact", f"${lo:,} - ${hi:,}"],
        ["Matched incident", wo.get("matched_incident") or "-"],
    ]
    table = Table(rows, colWidths=[120, 360])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    doc.build(
        [
            Paragraph("OvenMind — Maintenance Work Order", styles["Title"]),
            Paragraph("Auto-generated by the Work-Order Agent (simulated demo data)",
                      styles["Italic"]),
            Spacer(1, 16),
            table,
        ]
    )
    return str(path)
